language: cpp
dist: xenial
sudo: required

branches:
  only:
    - master
    
os:
  - linux

env:
  - CONFIG=Release

compiler:
  - clang
  - gcc

before_install:
  - QT_VERSION_MM=59
  - QT_VERSION_FULL=59-xenial
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-add-repository --yes ppa:beineri/opt-qt$QT_VERSION_FULL
      && sudo apt-get update -qq
      && sudo apt-get install -qq qt${QT_VERSION_MM}base qt${QT_VERSION_MM}script qt${QT_VERSION_MM}tools
      && export CMAKE_PREFIX_PATH=/opt/qt${QT_VERSION_MM}
      && sudo apt-get install mesa-common-dev libglu1-mesa-dev extra-cmake-modules;
    fi

before_script:
   - mkdir build
   - cd build
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DDISABLE_MAINTAINER_CFLAGS=off

script:
   - cmake --build . --config $CONFIG &&
     ctest --output-on-failure
